name: TypeScript Continuous Integration
run-name: Lint, Test and Build

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm i
      - run: npm run lint

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: pnpm i
      - run: npm run build

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm i
      - run: npx playwright install

        # xvfb-run needed to run virtual X-server for browser in CI context
      - run: xvfb-run npm run test
