name: TypeScript Continuous Integration
run-name: Lint, Test and Build

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Corepack enable
        shell: bash
        run: |
          npm i -g corepack@latest
          corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm i
      - run: pnpm lint

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Corepack enable
        shell: bash
        run: |
          npm i -g corepack@latest
          corepack enable


      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm i
      - run: pnpm build

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Corepack enable
        shell: bash
        run: |
          npm i -g corepack@latest
          corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm i
      - run: npx playwright install

        # xvfb-run needed to run virtual X-server for browser in CI context
      - run: xvfb-run pnpm test
